// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// baranov
double baranov(double log_f, double m, NumericVector sel, NumericVector b_a, double catches);
RcppExport SEXP _sraplus_baranov(SEXP log_fSEXP, SEXP mSEXP, SEXP selSEXP, SEXP b_aSEXP, SEXP catchesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type log_f(log_fSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sel(selSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b_a(b_aSEXP);
    Rcpp::traits::input_parameter< double >::type catches(catchesSEXP);
    rcpp_result_gen = Rcpp::wrap(baranov(log_f, m, sel, b_a, catches));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sraplus_baranov", (DL_FUNC) &_sraplus_baranov, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_sraplus(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
